pages:
  - name: Home
    # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
    hide-desktop-navigation: true
    columns:
      - size: small
        widgets:
          - type: calendar
            first-day-of-week: monday


      - size: full
        widgets:
          - type: monitor
            cache: 1m
            title: Services
            sites:
              - title: AdGuard
                url: http://192.168.10.20

      - size: small
        widgets:
          - type: weather
            location: Tampere, Finland
            units: metric
            hour-format: 24h

          - type: releases
            cache: 1d
            # Without authentication the Github API allows for up to 60 requests per hour. You can create a
            # read-only token from your Github account settings and use it here to increase the limit.
            # token: ...
            repositories:
              - glanceapp/glance
              - go-gitea/gitea
              - immich-app/immich
              - syncthing/syncthing

