---
- name: Install SSH on Almalinux LXC's
  hosts: dnslxc
  gather_facts: true
  tasks:
    - name: Update all packages
      ansible.builtin.dnf:
        name: '*'
        state: latest

    - name: Install openssh-server
      ansible.builtin.dnf:
        name: 'openssh-server'
        state: latest

    - name: Enable sshd service
      ansible.builtin.systemd_service:
        state: started
        enabled: true
        name: sshd
